#!/bin/bash
# Google OAuth Setup Helper for MR Shop
# This script helps you configure Google OAuth for development

echo "🔐 MR Shop Google OAuth Setup Helper"
echo "====================================="
echo ""
echo "Project: mr-shop-480319"
echo "Status: Development (Demo Mode Active)"
echo ""
echo "📋 What You Need to Do:"
echo ""
echo "Step 1: Go to Google Cloud Console"
echo "   URL: https://console.cloud.google.com"
echo ""
echo "Step 2: Select Your Project"
echo "   Project: mr-shop-480319"
echo ""
echo "Step 3: Create OAuth 2.0 Credentials"
echo "   Path: APIs & Services → Credentials → Create Credentials"
echo "   Type: OAuth 2.0 Client ID"
echo "   Application Type: Web Application"
echo ""
echo "Step 4: Add Authorized Origins"
echo "   - http://localhost:8000"
echo "   - http://localhost:3000"
echo "   - http://127.0.0.1:8000"
echo ""
echo "Step 5: Add Authorized Redirect URIs"
echo "   - http://localhost:8000/assets/html/auth.html"
echo "   - http://localhost:8000/callback"
echo "   - http://localhost:8000/assets/html/auth.html#google-callback"
echo ""
echo "Step 6: Copy Your Client ID"
echo "   Format: XXXXX-YYYYY.apps.googleusercontent.com"
echo ""
echo "Step 7: Update auth.js"
echo "   File: /assets/js/auth.js"
echo "   Line: ~337"
echo "   Replace: const CLIENT_ID = 'YOUR_CLIENT_ID_HERE';"
echo "   With: const CLIENT_ID = 'your-actual-client-id.apps.googleusercontent.com';"
echo ""
echo "Step 8: Done! Test your OAuth"
echo "   URL: http://localhost:8000/assets/html/auth.html#register"
echo "   Click 'Continue with Google'"
echo ""
echo "📌 Important Notes:"
echo "   - Demo mode is currently active (no real Google API needed)"
echo "   - Click 'Continue with Google' to test with demo users"
echo "   - Real OAuth will work after you add your Client ID"
echo ""
echo "✅ Setup Complete When You:"
echo "   ✓ Created OAuth 2.0 credentials in Google Cloud Console"
echo "   ✓ Copied your Client ID"
echo "   ✓ Updated the CLIENT_ID in /assets/js/auth.js"
echo "   ✓ Tested the OAuth flow"
echo ""
