#!/bin/bash

# MR Shop Google OAuth - HTTP Development Setup
# This script helps configure Google OAuth for HTTP localhost development

echo "🔐 MR Shop - Google OAuth HTTP Setup"
echo "====================================="
echo ""
echo "✅ For DEVELOPMENT (localhost), you can use HTTP!"
echo ""
echo "📋 ADD THESE URLS IN GOOGLE CLOUD CONSOLE:"
echo ""
echo "============================================"
echo "JAVASCRIPT ORIGINS (Allow these)"
echo "============================================"
echo ""
echo "http://localhost:8000"
echo "http://localhost:3000"
echo "http://127.0.0.1:8000"
echo ""
echo "============================================"
echo "REDIRECT URIs (Must add these)"
echo "============================================"
echo ""
echo "http://localhost:8000/assets/html/auth.html"
echo "http://localhost:8000/callback"
echo ""
echo "============================================"
echo ""
echo "📌 IMPORTANT:"
echo "   ✓ Copy EXACTLY as shown above"
echo "   ✓ Use HTTP (not HTTPS for localhost)"
echo "   ✓ Use port 8000 (must match your server)"
echo "   ✓ Click SAVE/CREATE after adding"
echo ""
echo "🔧 After adding URLs:"
echo "   1. Copy the Client ID shown"
echo "   2. Update /assets/js/auth.js line ~337"
echo "   3. Replace 'YOUR_CLIENT_ID_HERE' with your actual Client ID"
echo "   4. Save and test!"
echo ""
echo "🧪 Test URLs:"
echo "   http://localhost:8000/assets/html/auth.html#register"
echo "   http://localhost:8000/assets/html/oauth-test.html"
echo ""
